# configs/robot_config.yaml - 机器人配置
robot_params:
  robot_ip: "172.16.0.2"
  flask_port: 5000
  agentlace_port: 5555
  gripper_type: "Franka"
  use_simulation: false
  
camera_params:
  cam_high_topic: "/camera/color/image_raw"
  cam_low_topic: "/wrist_camera/color/image_raw" 
  image_size: [480, 640]
  fps: 30
  
# 网络配置
network_params:
  server_ip: "10.16.49.124"
  timeout: 30
  retry_attempts: 3
  
# ROS 话题配置
ros_topics:
  joint_states: "/franka_state_controller/joint_states"
  franka_states: "/franka_state_controller/franka_states" 
  gripper_action: "/franka_gripper/gripper_action"
  cartesian_impedance: "/cartesian_impedance_example_controller/equilibrium_pose"
